CREATE SEQUENCE IF NOT EXISTS employees_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS orders_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE employees
(
    id       BIGINT NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id              BIGINT NOT NULL,
    purchased_by_id BIGINT,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE widgets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    slug          VARCHAR(255),
    purchases     INTEGER                                 NOT NULL,
    inventory     INTEGER                                 NOT NULL,
    cost          DOUBLE PRECISION                        NOT NULL,
    image         VARCHAR(255),
    created_by_id BIGINT,
    CONSTRAINT pk_widgets PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PURCHASED_BY FOREIGN KEY (purchased_by_id) REFERENCES users (id);

ALTER TABLE widgets
    ADD CONSTRAINT FK_WIDGETS_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES employees (id);