CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    price      DOUBLE PRECISION                        NOT NULL,
    order_id   BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

ALTER TABLE widgets
    ADD description VARCHAR(255);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES widgets (id);